const commentsData = {
  comments: [
    "Hi",
    "Good morning",
    "Good evening",
    "Super",
    "Amazing",
    "Mass",
    "Wow",
    "Interesting",
    "Entertaining",
    "Loved it",
    "Good one",
    "Awesome",
    "Fantastic",
    "Epic",
    "Cool",
    "Hilarious",
    "Brilliant",
    "Nice one",
    "Mind-blowing",
    "Outstanding",
    "Classic",
    "Unbelievable",
    "Perfect",
    "Iconic",
    "Wonderful",
    "Heartwarming",
    "Inspirational",
    "Thrilling",
    "Chilling",
    "So funny",
    "Great work",
    "This scene gave me goosebumps",
    "Best episode so far",
    "What an incredible performance by the cast",
    "This dialogue is unforgettable",
    "The visuals are stunning",
    "I can't stop rewatching this moment",
    "Such an emotional scene",
    "This is why this show is a masterpiece",
    "The villain totally stole the show",
    "This episode deserves an award",
    "The plot twist was insane",
    "The background score is so powerful",
    "This movie is a cinematic gem",
    "What a fantastic ending",
    "The chemistry between the leads is perfect",
    "This is peak storytelling",
    "Every frame is a work of art",
    "The fight sequence was legendary",
    "I can't wait for the next season",
    "This is hands down the best series ever",
    "The direction is on another level",
    "This deserves a standing ovation",
    "Such a powerful message in this scene",
    "The cinematography is top-notch",
    "This deserves a rewatch for sure",
    "The way the story unfolded was brilliant",
    "I got chills watching this part",
    "The cast is so talented",
    "This deserves more recognition",
    "The nostalgia hit hard with this scene",
    "Your editing skills are insane",
    "I’ve been waiting for this upload all day",
    "You never fail to entertain us",
    "The humor in this video is unmatched",
    "This is why you're my favorite YouTuber",
    "Every second of this video was worth it",
    "Your storytelling is amazing",
    "This deserves a million views",
    "You always come up with such creative content",
    "The intro was hilarious",
    "This collab is epic",
    "Keep up the amazing work",
    "You just made my day with this upload",
    "Your content never disappoints",
    "The way you explain things is so relatable",
    "This is why you’re the best in the game",
    "Every video you post is gold",
    "Your channel is growing for a reason",
    "This video was a rollercoaster of emotions",
    "I’m sharing this with all my friends",
    "The editing on this video is next level",
    "Your energy is contagious",
    "I love how genuine you are",
    "You deserve all the success in the world",
    "This was so much fun to watch",
    "Your humor is on point",
    "This is why I subscribed to your channel",
    "Can’t wait for the next upload",
    "Your reactions are priceless",
    "This video made me laugh so hard",
    "This deserves to go viral",
    "I can’t believe how good this is",
    "This is trending for a reason",
    "This is breaking the internet",
    "This is what quality content looks like",
    "I’m so glad this showed up in my recommendations",
  ],
};



export function getRandomComment() {
  const randomIndex = Math.floor(Math.random() * commentsData.comments.length);
  return commentsData.comments[randomIndex];
}
